1

In [15]:
def fib(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a+b
    return a

%timeit fib(8)

545 ns ± 5.42 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
import numpy as np

def n_fib(n):
    A = np.array([0,1])
    for i in range(n):
        A = [A[1], A[0]+A[1]]
    return A[0]

%timeit n_fib(8)

2.72 µs ± 26 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
def fib(n):
    if n == 0 or n == 1:
        return n
    else:
        return fib(n-1)+fib(n-2)
    
%timeit fib(8)

7.87 µs ± 54.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
def fib(n):
    if n == 0: return 0

    n -= 2

    ca, cb, cc = sa, sb, sc = 1, 1, 0

    while n>0:
        if n & 1: 
            sa, sb, sc = (sa*ca + sb*cb), (sa*cb + sb*cc), (sb*cb + sc*cc)
        n >>= 1
        t = cb**2
        ca, cb, cc = (ca**2+t), (cb*(ca+cc)), (cc**2+t)

    return sa

%timeit fib(8)

3.29 µs ± 87.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


4

In [22]:
A = np.arange(1000)

for i in A:
    if i%2==1:
        A[i] = np.random.randint(1000)
print(A)

[  0 667   2 797   4 181   6 232   8 364  10 240  12 504  14 434  16 452
  18 978  20  51  22 662  24 518  26 447  28 279  30 947  32 856  34 248
  36 670  38 496  40 173  42 617  44 466  46 446  48 392  50 984  52 436
  54 682  56 535  58 845  60 282  62  96  64 400  66 524  68  29  70 229
  72 383  74 977  76 859  78  16  80 184  82 644  84 858  86 603  88 206
  90 952  92 421  94 185  96 710  98 282 100 110 102 969 104 835 106 881
 108 905 110 868 112 287 114 549 116 981 118 250 120 999 122 728 124 986
 126 340 128 804 130 474 132 546 134  44 136 720 138 253 140 671 142 125
 144 938 146 613 148 795 150 378 152 493 154 786 156 125 158  20 160 580
 162 939 164 914 166 221 168 528 170 359 172 650 174 440 176 475 178  59
 180 266 182 621 184 739 186 381 188 649 190 522 192 693 194 347 196  94
 198 486 200 354 202 522 204 711 206 136 208 237 210 508 212 137 214 774
 216 243 218 205 220  71 222  70 224 646 226 713 228 451 230 317 232 179
 234 177 236 746 238  75 240 735 242  89 244 566 24

5

In [28]:
A = np.arange(1000)
B = np.where(A%2==1, A, -1)

In [29]:
print(B)

[ -1   1  -1   3  -1   5  -1   7  -1   9  -1  11  -1  13  -1  15  -1  17
  -1  19  -1  21  -1  23  -1  25  -1  27  -1  29  -1  31  -1  33  -1  35
  -1  37  -1  39  -1  41  -1  43  -1  45  -1  47  -1  49  -1  51  -1  53
  -1  55  -1  57  -1  59  -1  61  -1  63  -1  65  -1  67  -1  69  -1  71
  -1  73  -1  75  -1  77  -1  79  -1  81  -1  83  -1  85  -1  87  -1  89
  -1  91  -1  93  -1  95  -1  97  -1  99  -1 101  -1 103  -1 105  -1 107
  -1 109  -1 111  -1 113  -1 115  -1 117  -1 119  -1 121  -1 123  -1 125
  -1 127  -1 129  -1 131  -1 133  -1 135  -1 137  -1 139  -1 141  -1 143
  -1 145  -1 147  -1 149  -1 151  -1 153  -1 155  -1 157  -1 159  -1 161
  -1 163  -1 165  -1 167  -1 169  -1 171  -1 173  -1 175  -1 177  -1 179
  -1 181  -1 183  -1 185  -1 187  -1 189  -1 191  -1 193  -1 195  -1 197
  -1 199  -1 201  -1 203  -1 205  -1 207  -1 209  -1 211  -1 213  -1 215
  -1 217  -1 219  -1 221  -1 223  -1 225  -1 227  -1 229  -1 231  -1 233
  -1 235  -1 237  -1 239  -1 241  -1 243  -1 245  -

6

In [ ]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

7

In [ ]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

8

In [43]:
def f(x,y):
    return x*y

b = np.fromfunction(f, (10,10), dtype=int)
print(b[1:,1:])

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


9 i 10


In [14]:
import numpy as np
array1 = np.array([10, 20, 25, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

indices = np.intersect1d(array1, array2, return_indices=True)
indices[0][indices[1]==indices[2]]

Array1:  [10 20 25 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


array([10])

11

In [49]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values: ", x[(x > 5) & (x < 30)])

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values:  [10 20 20]


12

In [15]:
a = np.random.rand(3,3)

In [16]:
a

array([], dtype=int64)